language: ruby
rvm:
  - 2.4.1
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
after_success:
  - bundle exec codeclimate-test-reporter
dist: trusty
cache: bundler
addons:
  code_climate:
    repo_token: 435c49a65f6c0f5ed67c45cfd60d36502c5f318c22b6468753421b8afa64b90a
