# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 181dd01a9ba4d1a73df49b57a42785a9b37211be2cf3a9160ab9694ea2352442aae547d01f0eaaf0505adef1660dc3f21dfbe68ee552262fea8f17899a7fb94a

test:
  secret_key_base: 6edf70286798a3a1a139429c2d8df6acc689fc9a3f982eed4a69ac3a5d8af6366a8fdca5487ed257d8305d08e82c3dd47e147bb475b653ac1f9ed2ecc9166d1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
